<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
</Project>
