<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Ulid" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="DynamicExpresso.Core" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Dc.Infrastructure.Tests" />
    <InternalsVisibleTo Include="Dc.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dc.Domain\Dc.Domain.csproj" />
    <ProjectReference Include="..\Dc.Opc.Abstractions\Dc.Opc.Abstractions.csproj" />
  </ItemGroup>
</Project>
